import type { Metadata } from "next";
import { Geist, Ubuntu, Inter } from "next/font/google";
import "../styles/globals.css";



const ubuntu = Ubuntu({
  weight: ["400", "700"],
  variable: "--font-ubuntu",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
